spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-mcsv
          uri: lb://user-mcsv
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
        - id: book-mcsv
          uri: lb://book-mcsv
          predicates:
            - Path=/api/book/**
          filters:
            - StripPrefix=2
        - id: loans-mcsv
          uri: lb://loans-mcsv
          predicates:
            - Path=/api/loans/**
          filters:
            - StripPrefix=2
        - id: notifications-mcsv
          uri: lb://notifications-mcsv
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=2

server:
  port: 8090
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
