spring:
  application:
    name: user-mcsv
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2-console
    jpa:
      hibernate:
        ddl-auto: create  # Puede ser update, validate, create, etc.
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect

server:
  port: ${PORT:0}
  error:
    include-stacktrace: never

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
  client:
    service-url.defaultzone: "http://localhost:8761/eureka"