spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-mcsv
          uri: lb://user-mcsv
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
server:
  port: 8090
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
